language: php
sudo: required
dist: trusty
php: '7.0'
install:
  - composer install  --no-interaction
  # Install PHPCS
  - composer global require "squizlabs/php_codesniffer *"
env:
  global:
    - setup=basic
